
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1408/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Linux - 6.8.0-31-generic - x86_64
...
